CREATE TABLE users (
 id UUID PRIMARY KEY,
 firebase_uid VARCHAR(128) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 phone VARCHAR(30) NOT NULL DEFAULT '',
 photo_url VARCHAR(2000) NOT NULL DEFAULT '',
 default_currency VARCHAR(3) NOT NULL DEFAULT 'INR',
 upi_id VARCHAR(120) NOT NULL DEFAULT '',
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 version BIGINT NOT NULL DEFAULT 0
);
